/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const TransactionStatus = IDL.Variant({
  'pending' : IDL.Null,
  'success' : IDL.Null,
  'failed' : IDL.Null,
});
export const TransactionType = IDL.Variant({
  'billPayment' : IDL.Null,
  'topUp' : IDL.Null,
  'receive' : IDL.Null,
  'send' : IDL.Null,
  'recharge' : IDL.Null,
});
export const Time = IDL.Int;
export const Transaction = IDL.Record({
  'id' : IDL.Nat,
  'status' : TransactionStatus,
  'note' : IDL.Opt(IDL.Text),
  'type' : TransactionType,
  'fromUpiId' : IDL.Text,
  'toUpiId' : IDL.Text,
  'timestamp' : Time,
  'amount' : IDL.Float64,
});
export const Profile = IDL.Record({
  'name' : IDL.Text,
  'upiId' : IDL.Text,
  'phone' : IDL.Text,
  'walletBalance' : IDL.Float64,
});
export const NotificationType = IDL.Variant({
  'requestAccepted' : IDL.Null,
  'requestReceived' : IDL.Null,
  'transactionAlert' : IDL.Null,
});
export const Notification = IDL.Record({
  'id' : IDL.Nat,
  'type' : NotificationType,
  'isRead' : IDL.Bool,
  'message' : IDL.Text,
  'timestamp' : Time,
});
export const RequestStatus = IDL.Variant({
  'pending' : IDL.Null,
  'accepted' : IDL.Null,
  'declined' : IDL.Null,
});
export const MoneyRequest = IDL.Record({
  'id' : IDL.Nat,
  'status' : RequestStatus,
  'note' : IDL.Opt(IDL.Text),
  'fromUpiId' : IDL.Text,
  'toUpiId' : IDL.Text,
  'timestamp' : Time,
  'amount' : IDL.Float64,
});
export const PlatformStats = IDL.Record({
  'totalWalletBalance' : IDL.Float64,
  'totalVolume' : IDL.Float64,
  'totalUsers' : IDL.Nat,
  'totalTransactions' : IDL.Nat,
});
export const BillCategory = IDL.Variant({
  'dth' : IDL.Null,
  'gas' : IDL.Null,
  'electricity' : IDL.Null,
  'mobile' : IDL.Null,
  'water' : IDL.Null,
});
export const BillPayment = IDL.Record({
  'provider' : IDL.Text,
  'billNumber' : IDL.Text,
  'category' : BillCategory,
  'amount' : IDL.Float64,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'acceptRequest' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
  'adminAdjustUserBalance' : IDL.Func([IDL.Principal, IDL.Float64], [], []),
  'adminAssignUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'changeMpin' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'changePassword' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'createOrUpdateProfile' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'declineRequest' : IDL.Func([IDL.Nat], [], []),
  'getAllTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'getAllUsers' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, Profile))],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(Profile)], []),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
  'getPendingMoneyRequests' : IDL.Func([], [IDL.Vec(MoneyRequest)], ['query']),
  'getPlatformStats' : IDL.Func([], [PlatformStats], ['query']),
  'getProfile' : IDL.Func([], [IDL.Opt(Profile)], []),
  'getRecentTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'getTransactionHistory' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'getUnreadNotificationCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func([IDL.Principal], [IDL.Opt(Profile)], ['query']),
  'getWalletBalance' : IDL.Func([], [IDL.Float64], ['query']),
  'getWalletBalanceByPhone' : IDL.Func([IDL.Text], [IDL.Float64], ['query']),
  'getWalletBalanceByUpiId' : IDL.Func([IDL.Text], [IDL.Float64], ['query']),
  'hasAccount' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'login' : IDL.Func([IDL.Text, IDL.Text], [IDL.Opt(Profile)], []),
  'lookupProfileByPhone' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(IDL.Record({ 'name' : IDL.Text, 'upiId' : IDL.Text }))],
      ['query'],
    ),
  'lookupProfileByUpiId' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(IDL.Record({ 'name' : IDL.Text, 'upiId' : IDL.Text }))],
      ['query'],
    ),
  'markNotificationAsRead' : IDL.Func([IDL.Nat], [], []),
  'payBill' : IDL.Func([BillPayment], [], []),
  'requestMoney' : IDL.Func([IDL.Text, IDL.Float64, IDL.Opt(IDL.Text)], [], []),
  'saveCallerUserProfile' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'sendMoney' : IDL.Func(
      [IDL.Text, IDL.Float64, IDL.Opt(IDL.Text), IDL.Bool],
      [],
      [],
    ),
  'signup' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
  'topUpWallet' : IDL.Func([IDL.Float64], [], []),
  'verifyMpin' : IDL.Func([IDL.Text], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const TransactionStatus = IDL.Variant({
    'pending' : IDL.Null,
    'success' : IDL.Null,
    'failed' : IDL.Null,
  });
  const TransactionType = IDL.Variant({
    'billPayment' : IDL.Null,
    'topUp' : IDL.Null,
    'receive' : IDL.Null,
    'send' : IDL.Null,
    'recharge' : IDL.Null,
  });
  const Time = IDL.Int;
  const Transaction = IDL.Record({
    'id' : IDL.Nat,
    'status' : TransactionStatus,
    'note' : IDL.Opt(IDL.Text),
    'type' : TransactionType,
    'fromUpiId' : IDL.Text,
    'toUpiId' : IDL.Text,
    'timestamp' : Time,
    'amount' : IDL.Float64,
  });
  const Profile = IDL.Record({
    'name' : IDL.Text,
    'upiId' : IDL.Text,
    'phone' : IDL.Text,
    'walletBalance' : IDL.Float64,
  });
  const NotificationType = IDL.Variant({
    'requestAccepted' : IDL.Null,
    'requestReceived' : IDL.Null,
    'transactionAlert' : IDL.Null,
  });
  const Notification = IDL.Record({
    'id' : IDL.Nat,
    'type' : NotificationType,
    'isRead' : IDL.Bool,
    'message' : IDL.Text,
    'timestamp' : Time,
  });
  const RequestStatus = IDL.Variant({
    'pending' : IDL.Null,
    'accepted' : IDL.Null,
    'declined' : IDL.Null,
  });
  const MoneyRequest = IDL.Record({
    'id' : IDL.Nat,
    'status' : RequestStatus,
    'note' : IDL.Opt(IDL.Text),
    'fromUpiId' : IDL.Text,
    'toUpiId' : IDL.Text,
    'timestamp' : Time,
    'amount' : IDL.Float64,
  });
  const PlatformStats = IDL.Record({
    'totalWalletBalance' : IDL.Float64,
    'totalVolume' : IDL.Float64,
    'totalUsers' : IDL.Nat,
    'totalTransactions' : IDL.Nat,
  });
  const BillCategory = IDL.Variant({
    'dth' : IDL.Null,
    'gas' : IDL.Null,
    'electricity' : IDL.Null,
    'mobile' : IDL.Null,
    'water' : IDL.Null,
  });
  const BillPayment = IDL.Record({
    'provider' : IDL.Text,
    'billNumber' : IDL.Text,
    'category' : BillCategory,
    'amount' : IDL.Float64,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'acceptRequest' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
    'adminAdjustUserBalance' : IDL.Func([IDL.Principal, IDL.Float64], [], []),
    'adminAssignUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'changeMpin' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'changePassword' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'createOrUpdateProfile' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'declineRequest' : IDL.Func([IDL.Nat], [], []),
    'getAllTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
    'getAllUsers' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, Profile))],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(Profile)], []),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
    'getPendingMoneyRequests' : IDL.Func(
        [],
        [IDL.Vec(MoneyRequest)],
        ['query'],
      ),
    'getPlatformStats' : IDL.Func([], [PlatformStats], ['query']),
    'getProfile' : IDL.Func([], [IDL.Opt(Profile)], []),
    'getRecentTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
    'getTransactionHistory' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
    'getUnreadNotificationCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func([IDL.Principal], [IDL.Opt(Profile)], ['query']),
    'getWalletBalance' : IDL.Func([], [IDL.Float64], ['query']),
    'getWalletBalanceByPhone' : IDL.Func([IDL.Text], [IDL.Float64], ['query']),
    'getWalletBalanceByUpiId' : IDL.Func([IDL.Text], [IDL.Float64], ['query']),
    'hasAccount' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'login' : IDL.Func([IDL.Text, IDL.Text], [IDL.Opt(Profile)], []),
    'lookupProfileByPhone' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(IDL.Record({ 'name' : IDL.Text, 'upiId' : IDL.Text }))],
        ['query'],
      ),
    'lookupProfileByUpiId' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(IDL.Record({ 'name' : IDL.Text, 'upiId' : IDL.Text }))],
        ['query'],
      ),
    'markNotificationAsRead' : IDL.Func([IDL.Nat], [], []),
    'payBill' : IDL.Func([BillPayment], [], []),
    'requestMoney' : IDL.Func(
        [IDL.Text, IDL.Float64, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'sendMoney' : IDL.Func(
        [IDL.Text, IDL.Float64, IDL.Opt(IDL.Text), IDL.Bool],
        [],
        [],
      ),
    'signup' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
    'topUpWallet' : IDL.Func([IDL.Float64], [], []),
    'verifyMpin' : IDL.Func([IDL.Text], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };