/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type BillCategory = { 'dth' : null } |
  { 'gas' : null } |
  { 'electricity' : null } |
  { 'mobile' : null } |
  { 'water' : null };
export interface BillPayment {
  'provider' : string,
  'billNumber' : string,
  'category' : BillCategory,
  'amount' : number,
}
export interface MoneyRequest {
  'id' : bigint,
  'status' : RequestStatus,
  'note' : [] | [string],
  'fromUpiId' : string,
  'toUpiId' : string,
  'timestamp' : Time,
  'amount' : number,
}
export interface Notification {
  'id' : bigint,
  'type' : NotificationType,
  'isRead' : boolean,
  'message' : string,
  'timestamp' : Time,
}
export type NotificationType = { 'requestAccepted' : null } |
  { 'requestReceived' : null } |
  { 'transactionAlert' : null };
export interface PlatformStats {
  'totalWalletBalance' : number,
  'totalVolume' : number,
  'totalUsers' : bigint,
  'totalTransactions' : bigint,
}
export interface Profile {
  'name' : string,
  'upiId' : string,
  'phone' : string,
  'walletBalance' : number,
}
export type RequestStatus = { 'pending' : null } |
  { 'accepted' : null } |
  { 'declined' : null };
export type Time = bigint;
export interface Transaction {
  'id' : bigint,
  'status' : TransactionStatus,
  'note' : [] | [string],
  'type' : TransactionType,
  'fromUpiId' : string,
  'toUpiId' : string,
  'timestamp' : Time,
  'amount' : number,
}
export type TransactionStatus = { 'pending' : null } |
  { 'success' : null } |
  { 'failed' : null };
export type TransactionType = { 'billPayment' : null } |
  { 'topUp' : null } |
  { 'receive' : null } |
  { 'send' : null } |
  { 'recharge' : null };
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'acceptRequest' : ActorMethod<[bigint, boolean], undefined>,
  'adminAdjustUserBalance' : ActorMethod<[Principal, number], undefined>,
  'adminAssignUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createOrUpdateProfile' : ActorMethod<[string, string], undefined>,
  'declineRequest' : ActorMethod<[bigint], undefined>,
  'getAllTransactions' : ActorMethod<[], Array<Transaction>>,
  'getAllUsers' : ActorMethod<[], Array<[Principal, Profile]>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [Profile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getNotifications' : ActorMethod<[], Array<Notification>>,
  'getPendingMoneyRequests' : ActorMethod<[], Array<MoneyRequest>>,
  'getPlatformStats' : ActorMethod<[], PlatformStats>,
  'getProfile' : ActorMethod<[], [] | [Profile]>,
  'getRecentTransactions' : ActorMethod<[], Array<Transaction>>,
  'getTransactionHistory' : ActorMethod<[], Array<Transaction>>,
  'getUnreadNotificationCount' : ActorMethod<[], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [Profile]>,
  'getWalletBalance' : ActorMethod<[], number>,
  'getWalletBalanceByPhone' : ActorMethod<[string], number>,
  'getWalletBalanceByUpiId' : ActorMethod<[string], number>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'lookupProfileByUpiId' : ActorMethod<
    [string],
    [] | [{ 'name' : string, 'upiId' : string }]
  >,
  'markNotificationAsRead' : ActorMethod<[bigint], undefined>,
  'payBill' : ActorMethod<[BillPayment], undefined>,
  'requestMoney' : ActorMethod<[string, number, [] | [string]], undefined>,
  'saveCallerUserProfile' : ActorMethod<[string, string], undefined>,
  'sendMoney' : ActorMethod<
    [string, number, [] | [string], boolean],
    undefined
  >,
  'topUpWallet' : ActorMethod<[number], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];